"""dd utorial model

Revision ID: fd8c5523aa6e
Revises: 
Create Date: 2023-05-16 14:48:50.452365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd8c5523aa6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id_1', sa.Integer(), nullable=False))
    op.drop_index('ix_user_id', table_name='user')
    op.create_index(op.f('ix_user_id_1'), 'user', ['id_1'], unique=False)
    op.drop_column('user', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_user_id_1'), table_name='user')
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.drop_column('user', 'id_1')
    # ### end Alembic commands ###
